name: First Workflow

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        echo "Run First Test"
  # call-workflow-gitops-release:
  #   uses: neosec-com/clickhouse-operator/.github/workflows/gitops-release.yml@test
    #     client-payload: '{"gitops_release": "First Workflow"}'
