name: First Workflow

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        echo "Run First Test"
    # - name: Workflow GitOps Release
    #   uses: peter-evans/repository-dispatch@v2
    #   with:
    #     event-type: gitops-release
    #     client-payload: '{"gitops_release": "true"}'